### PR TITLE
08 lab development

### PR DESCRIPTION
**Pull request by jdkent**
Reformatted to use optseq2 and wrote out some problems for the students to solve

### CODE REVIEW

**Comment by mwvoss** [comment]
Nice job! My notes:

“Building an Experiment”
-instead of number of stimuli, number of conditions or event types (how optseq refers)?  makes the use more general when the same condition can have multiple stimulus types.
-“the number of presentations for each stimulus (40)” -> “for each condition”

optseq2
-they will not have the program before starting the lab, suggest having a prep cell to download the program; may setup to put into its own directory for lab 08
-or write into the lab to download and copy paste into the lab directory and make it accessible to use in the notebook; i had some trouble getting the program to run for me and didn’t find the solution. I might be missing something easy with sourcing or permissions though. Happy to test this as new user once you revise. 

Suppress output of optseq when you load for the class

Problem sets look good. In class emphasize that even if someone is going to analyze data they have or resting state, they should still try to generate a task design for a task they may be interested in running some day.

**Comment by mwvoss** [comment]
only one last thing: check second part of sentence, "To give some intuition, a small variance reduction factor means the conditions are highly correlated with each other  ... , whereas a small variance reduction factor means the conditions are largely independent  .. ."

**Comment by jdkent** [comment]
Should be good to go, I changed references from stimulus to event type where it makes sense to do so, I tested it on the virtual machine and it appears to be working fine. I can merge for you to test if it's too complicated for you to test with my fork.

**Comment by mwvoss** [comment]
yep go forward to merge after checking my last comment. good to go.

**Comment by jdkent** [comment]
Good catch!

**Pull request merged**
